export default function Content() {
    return (
        <div className="container mx-auto py-6 w-screen max-w-[1500px] px-6 xl:px-20">
            <div className="bg-white border p-10 shadow rounded-lg max-w-7xl mx-auto">
                <h1 className="text-center text-3xl font-bold mb-2 text-gray-600">Creating video from text </h1>
                <h2 className="text-center text-xl text-gray-500">Sora is an AI model that can create realistic and imaginative scenes from text instructions.</h2>
                <h2 className="text-center text-xl text-gray-500">Videos generated by Sora can be viewed here <a className="text-red-500" href="/feeds">www.soravid.net</a></h2>
                <div className="flex justify-center pt-10 mb-10">
                    <a 
                        href = "/feeds"
                        className="group relative inline-flex items-center overflow-hidden rounded-full border-2 border-fuchsia-800 px-12 py-3 text-lg font-medium text-fuchsia-800 hover:bg-gray-50 hover:text-white"
                    >
                        <span className="duration-400 ease absolute left-0 top-1/2 block h-0 w-full bg-fuchsia-800 opacity-100 transition-all group-hover:top-0 group-hover:h-full"></span>
                        <span className="ease absolute right-0 flex h-10 w-10 translate-x-full transform items-center justify-start duration-500 group-hover:-translate-x-2">
                        <svg className="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M14 5l7 7m0 0l-7 7m7-7H3"></path></svg>
                        </span>
                        <span className="relative transform duration-700 group-hover:-translate-x-3">View Sora Videos And Prompts</span>
                    </a>
                </div>

                <h1 className="text-center text-3xl font-bold mb-2 text-gray-600">How to access Sora </h1>
                <h2 className="text-center text-xl text-gray-500">Sora is becoming available to red teamers to assess critical areas for harms or risks.</h2>
                <h2 className="text-center text-xl text-gray-500">Currently, we do not have a specific timeline or further details to provide regarding the wider public release of Sora.</h2>
                <div className="flex pt-10 justify-center">
                    <a 
                        href = "/feeds"
                        className="group relative inline-flex items-center overflow-hidden rounded-full border-2 border-fuchsia-800 px-12 py-3 text-lg font-medium text-fuchsia-800 hover:bg-gray-50 hover:text-white"
                    >
                        <span className="duration-400 ease absolute left-0 top-1/2 block h-0 w-full bg-fuchsia-800 opacity-100 transition-all group-hover:top-0 group-hover:h-full"></span>
                        <span className="ease absolute right-0 flex h-10 w-10 translate-x-full transform items-center justify-start duration-500 group-hover:-translate-x-2">
                        <svg className="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M14 5l7 7m0 0l-7 7m7-7H3"></path></svg>
                        </span>
                        <span className="relative transform duration-700 group-hover:-translate-x-3">Try OpenAI Sora</span>
                    </a>
                </div>
            </div>
        </div>
    )
}